sudo: false
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - latest

matrix:
    fast_finish: true
    allow_failures:
        - php: latest

script:
  - php -dshort_open_tag=Off -dmagic_quotes_gpc=Off tests/index.php
